DEFLNG A-Z
OPTION _EXPLICIT
$CONSOLE:ONLY

$IF VERSION < 4.3.0 THEN
    $ERROR "The Libraries Pack add-on needs at least QB64-PE v4.3.0"
$END IF

$USELIBRARY:'a740g/Catch'

TEST_ENABLE_ERROR_HANDLER

TEST_ENABLE_COLOR _FALSE
TEST_ENABLE_EXIT_ON_END _FALSE
TEST_BEGIN_ALL

TEST_CASE_BEGIN "My Test Case"
TEST_CHECK 1 = 1, "This should pass"
TEST_REQUIRE 2 > 1, "This is required"
TEST_CASE_END

TEST_END_ALL

